title: Mike Brown # your name (or website title) here
logo: "/images/1525123996944.jpeg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I am a Data Science professional who enjoys solving problems to make life easier for my clients by building tools, providing insights, and optimizing workflows.
  <br><br>
  I am skilled in Python,VBA,Excel,SQL,Tableau, Power BI and more.
  <br><br>
  <a href="https://www.linkedin.com/in/michael-brown-67340b142">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
