title: Mike Brown # your name (or website title) here
logo: "/images/1525123996944.jpeg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! As a data science professional, I am passionate about solving complex problems for my clients. 
  I enjoy building tools that automate processes, providing insights to improve decision-making, and optimizing workflows to increase efficiency. 
  I'm skilled in Python, VBA, Excel, SQL, Tableau, Power BI, and I am always looking for new tools and opportunities to expand my knowledge. 
  My goal is to make life easier for my clients by developing solutions to thier data driven problems.
  <br><br>
  
  <a href="https://www.linkedin.com/in/michael-brown-67340b142">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
